### ISSUE TITLE
dtrace-provide module error when using latest node version

### ISSUE THREAD

**Issue by senthil5053** [joyent/node-ldapjs#462]
I'm using node v8.9.4, npm v5.6.0. After updating node version from v6.11.4 to v8.9.4 I get the following error:

`Error: The module '/Users/vananse/Senthil/Verizon/Sensity/GitHub/DevelopBranch/Farallones/api_tests/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vananse/Senthil/Verizon/Sensity/GitHub/DevelopBranch/Farallones/api_tests/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
Error: The module '/Users/vananse/Senthil/Verizon/Sensity/GitHub/DevelopBranch/Farallones/api_tests/node_modules/ldapjs/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vananse/Senthil/Verizon/Sensity/GitHub/DevelopBranch/Farallones/api_tests/node_modules/ldapjs/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vananse/Senthil/Verizon/Sensity/GitHub/DevelopBranch/Farallones/api_tests/node_modules/ldapjs/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vananse/Senthil/Verizon/Sensity/GitHub/DevelopBranch/Farallones/api_tests/node_modules/ldapjs/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' }`

Can someone help here to resolve this ?

**Comment by MichaelErmer** [comment]
Did u try removing `node_modules`?

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
